name: Check File Name

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
  push:
    branches:
      - main

jobs:
  check_file_name:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Check file names
      id: check_files
      run: |
        for file in $(git diff --name-only HEAD^..HEAD)
        do
          if [[ $file =~ [^a-z0-9_\-./] ]]; then
            echo "File name contains invalid characters: $file"
            echo "::set-output name=comment::Invalid characters found in file name: $file"
            exit 1
          fi
        done
        
    - name: Comment on PR
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const comment = `@${github.context.actor} Invalid characters found in file names:\n\n${github.context.workflow.runs[0].outputs.comment}`;
          const { owner, repo, number } = github.context.issue;
          github.issues.createComment({
            owner: owner,
            repo: repo,
            issue_number: number,
            body: comment
          });
