name: Check File Name

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
  push:
    branches:
      - main

jobs:
  check_file_name:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Get changed files
      id: file_changes
      run: |
        echo "::set-output name=files::$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})"
        
    - name: Check file names
      run: |
        for file in ${{ steps.file_changes.outputs.files }}
        do
          if echo "$file" | grep -q '[^a-z0-9_\-./]'; then
            echo "File name contains invalid characters: $file"
            echo "::error file=$file::File name contains invalid characters"
            exit 1
          fi
        done
